const set1 = [
  {
    questionNo: 1,
    question:
      'Virgin Trains, Virgin Atlantic and Virgin Racing, are all companies owned by which famous entrepreneur?',
    answers: ['Alan Sugar', 'Richard Branson', 'Donald Trump', 'Bill Gates'],
    correct: 'Richard Branson',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 2,
    question:
      'Where is the train station "Llanfair­pwllgwyngyll­gogery­chwyrn­drobwll­llan­tysilio­gogo­goch"?',
    answers: ['Denmark', 'Wales', 'Moldova', 'Czech Republic'],
    correct: 'Wales',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 3,
    question:
      'Which company did Valve cooperate with in the creation of the Vive?',
    answers: ['Google', 'Oculus', 'HTC', 'Razer'],
    correct: 'HTC',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 4,
    question: "What's the name of Batman's  parents?",
    answers: [
      'Joey and Jackie',
      'Thomas and Martha',
      'Jason and Sarah',
      'Todd and Mira',
    ],
    correct: 'Thomas and Martha',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 5,
    question: 'What is the most common surname Wales?',
    answers: ['Davies', 'Jones', 'Williams', 'Evans'],
    correct: 'Jones',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 6,
    question:
      'What was the name of the WWF professional wrestling tag team made up of the wrestlers Ax and Smash?',
    answers: [
      'Demolition',
      'The Dream Team',
      'The Bushwhackers',
      'The British Bulldogs',
    ],
    correct: 'Demolition',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 7,
    question:
      'What name represents the letter "M" in the NATO phonetic alphabet?',
    answers: ['Mike', 'Matthew', 'Mark', 'Max'],
    correct: 'Mike',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 8,
    question: 'What is the first book of the Old Testament?',
    answers: ['Exodus', 'Leviticus', 'Numbers', 'Genesis'],
    correct: 'Genesis',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 9,
    question:
      'In the video-game franchise Kingdom Hearts, the main protagonist, carries a weapon with what shape?',
    answers: ['Sword', 'Key', 'Pen', 'Cellphone'],
    correct: 'Key',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: 10,
    question:
      'Which best selling toy of 1983 caused hysteria, resulting in riots breaking out in stores?',
    answers: [
      'Transformers',
      'Care Bears',
      'Cabbage Patch Kids',
      'Rubik’s Cube',
    ],
    correct: 'Cabbage Patch Kids',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '11',
    question: 'What does a funambulist walk on?',
    answers: ['A Tight Rope', 'Broken Glass', 'Balls', 'The Moon'],
    correct: 'A Tight Rope',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '12',
    question: 'In past times, what would a gentleman keep in his fob pocket?',
    answers: ['Money', 'Watch', 'Keys', 'Notebook'],
    correct: 'Watch',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '13',
    question: 'Area 51 is located in which US state?',
    answers: ['Arizona', 'New Mexico', 'Utah', 'Nevada'],
    correct: 'Nevada',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '14',
    question: 'How would one say goodbye in Spanish?',
    answers: [' Hola', 'Adiós', 'Au Revoir', 'Salir'],
    correct: 'Adiós',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '15',
    question: 'What is the largest organ of the human body?',
    answers: ['Heart', 'large Intestine', 'Skin', 'Liver'],
    correct: 'Skin',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '16',
    question: 'Which sign of the zodiac is represented by the Crab?',
    answers: ['Libra', 'Cancer', 'Virgo', 'Sagittarius'],
    correct: 'Cancer',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '17',
    question: 'On a dartboard, what number is directly opposite No. 1?',
    answers: ['19', '20', '12', '15'],
    correct: '19',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '18',
    question:
      "What does the 'S' stand for in the abbreviation SIM, as in SIM card? ",
    answers: ['Single', 'Secure', 'Subscriber', 'Solid'],
    correct: 'Subscriber',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '19',
    question:
      "What word represents the letter 'T' in the NATO phonetic alphabet?",
    answers: ['Tango', 'Target', 'Taxi', 'Turkey'],
    correct: 'Tango',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '20',
    question: 'Which American president appears on a one dollar bill?',
    answers: [
      'George Washington',
      'Thomas Jefferson',
      'Abraham Lincoln',
      'Benjamin Franklin',
    ],
    correct: 'George Washington',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '21',
    question: 'What is "dabbing"?',
    answers: ['A medical procedure', 'A dance', 'A sport', 'A language'],
    correct: 'A dance',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '22',
    question: 'What is the name of the Jewish New Year?',
    answers: ['Elul', 'Rosh Hashanah', 'New Year', 'Succoss'],
    correct: 'Rosh Hashanah',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '23',
    question: 'Which one of the following rhythm games was made by Harmonix?',
    answers: [
      'Dance Dance Revolution',
      'Meat Beat Mania',
      'Rock Band',
      'Guitar Hero Live',
    ],
    correct: 'Rock Band',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '24',
    question:
      "What type of animal was Harambe, who was shot after a child fell into it's enclosure at the Cincinnati Zoo?",
    answers: ['Tiger', 'Panda', 'Gorilla', 'Crocodile'],
    correct: 'Gorilla',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '25',
    question: 'Red Vines is a brand of what type of candy?',
    answers: ['Lollipop', 'Chocolate', 'Licorice', 'Bubblegum'],
    correct: 'Licorice',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '26',
    question: 'What is the nickname of the US state of California?',
    answers: ['Golden State', 'Sunshine State', 'Bay State', 'Treasure State'],
    correct: 'Golden State',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '27',
    question: "What is on display in the Madame Tussaud's museum in London?",
    answers: [
      'Designer clothing',
      'Unreleased film reels',
      'Vintage cars',
      'Wax sculptures',
    ],
    correct: 'Wax sculptures',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '28',
    question:
      'What was the nickname given to the Hughes H-4 Hercules, a heavy transport flying boat which achieved flight in 1947?',
    answers: ["Noah's Ark", 'Fat Man', 'Spruce Goose', 'Trojan Horse'],
    correct: 'Spruce Goose',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '29',
    question: 'Which of these colours is NOT featured in the logo for Google?',
    answers: ['Yellow', 'Blue', 'Green', 'Pink'],
    correct: 'Pink',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '30',
    question: 'What is the French word for "hat"?',
    answers: ['Écharpe', 'Chapeau', 'Bonnet', ' Casque'],
    correct: 'Chapeau',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '31',
    question: 'Five dollars is worth how many nickles?',
    answers: ['100', '50', '25', '69'],
    correct: '100',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '32',
    question: 'Who is depicted on the US hundred dollar bill?',
    answers: [
      'George Washington',
      'Abraham Lincoln',
      'Benjamin Franklin',
      'Thomas Jefferson',
    ],
    correct: 'Benjamin Franklin',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '33',
    question: 'What do the letters in the GMT time zone stand for?',
    answers: [
      'Greenwich Mean Time',
      'Global Meridian Time',
      'General Median Time',
      'Glasgow Man Time',
    ],
    correct: 'Greenwich Mean Time',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '34',
    question: 'Which one of these is not a typical European sword design?',
    answers: ['Scimitar', 'Falchion', 'Ulfberht', 'Flamberge'],
    correct: 'Scimitar',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '35',
    question:
      'According to Sherlock Holmes, "If you eliminate the impossible, whatever remains, however improbable, must be the..."',
    answers: ['Answer', 'Cause', 'Truth', 'Source'],
    correct: 'Truth',
    questionId: '3410327',
  },
  {
    questionNo: '36',
    question: 'What is the name of Poland in Polish?',
    answers: ['Pupcia', 'Polska', 'Polszka', 'Póland'],
    correct: 'Polska',
    questionId: '3542596',
  },
  {
    questionNo: '37',
    question: 'The New York Times slogan is, “All the News That’s Fit to…”',
    answers: ['Digest', 'Look', 'Read', 'Print'],
    correct: 'Print',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '38',
    question: 'What do the letters of the fast food chain KFC stand for?',
    answers: [
      'Kentucky Fresh Cheese',
      'Kentucky Fried Chicken',
      'Kibbled Freaky Cow',
      'Kiwi Food Cut',
    ],
    correct: 'Kentucky Fried Chicken',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '39',
    question: "Which restaurant's mascot is a clown?",
    answers: ['Whataburger', 'Burger King', "McDonald's", 'Sonic'],
    correct: "McDonald's",
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '40',
    question: 'What color is the "Ex" in FedEx Ground?',
    answers: ['Red', 'Light Blue', 'Orange', 'Green'],
    correct: 'Green',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '41',
    question: 'How tall is the Burj Khalifa?',
    answers: ['2,722 ft', '2,717 ft', '2,546 ft', '3,024 ft'],
    correct: '2,722 ft',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '42',
    question:
      'Which of the following card games revolves around numbers and basic math?',
    answers: ['Go Fish', 'Twister', 'Uno', 'Munchkin'],
    correct: 'Uno',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '43',
    question:
      'What machine element is located in the center of fidget spinners?',
    answers: ['Axles', 'Gears', 'Belts', 'Bearings'],
    correct: 'Bearings',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '44',
    question: 'Which sign of the zodiac comes between Virgo and Scorpio?',
    answers: ['Gemini', 'Taurus', 'Libra', 'Capricorn'],
    correct: 'Libra',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '45',
    question: 'Which of the following presidents is not on Mount Rushmore?',
    answers: [
      'Theodore Roosevelt',
      'Abraham Lincoln',
      'John F. Kennedy',
      'Thomas Jefferson',
    ],
    correct: 'John F. Kennedy',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '46',
    question: 'What is Tasmania?',
    answers: [
      "A flavor of Ben and Jerry's ice-cream",
      'An Australian State',
      'A Psychological Disorder',
      'The Name of a Warner Brothers Cartoon Character',
    ],
    correct: 'An Australian State',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '47',
    question: 'What company developed the vocaloid Hatsune Miku?',
    answers: ['Sega', 'Sony', 'Crypton Future Media', 'Yamaha Corporation'],
    correct: 'Crypton Future Media',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '48',
    question:
      'Which country, not including Japan, has the most people of japanese decent?',
    answers: ['Brazil', 'China', 'South Korea', 'United States of America'],
    correct: 'Brazil',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '49',
    question: 'Which candy is NOT made by Mars?',
    answers: ["MandM's", 'Almond Joy', 'Twix', 'Snickers'],
    correct: 'Almond Joy',
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
  {
    questionNo: '50',
    question: 'In which fast food chain can you order a Jamocha Shake?',
    answers: ["McDonald's", 'Burger King', "Arby's", "Wendy's"],
    correct: "Arby's",
    questionId: require('crypto').randomBytes(4).toString('hex'),
  },
];

export default set1;
